### ISSUE TITLE
Note tails are visible in "Hide opponent notes in middlescroll" when they shouldn't.

### ISSUE THREAD

**Issue by tanooki1212** [weuz-github/FNF-OSEngine#11]
### Describe your bug here.

Note tails are visible, may I say more
![Screenshot (72)](https://user-images.githubusercontent.com/61921586/166171071-40afc9b4-6618-4225-9dee-a0c28a9605a3.png)
![Screenshot (70)](https://user-images.githubusercontent.com/61921586/166171073-80a27a8b-12b4-44f8-a3f9-b5f465ea8fe8.png)
![Screenshot (71)](https://user-images.githubusercontent.com/61921586/166171075-d2f050c8-a5ce-4fa5-b68a-783c916548bc.png)
?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the build.

**Comment by weuz-github** [comment]
fixing rn
