### ISSUE TITLE
can't press 7

### ISSUE THREAD

**Issue by Lorekeeper49** [weuz-github/FNF-OSEngine#15]
### Describe your bug here.

the button I have to go into the chart editor is 7 like it normally is for all other fnf stuff, but for some reason, 7 won't take me into the chart editor, the only way I can go into the chart editor is if I go into the freeplay menu and press shift+enter on the song I want to chart

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by snazzyostrich** [comment]
did you turn on "disable debugmenu buttons"
if so, go to the json and turn it off

**Comment by Lorekeeper49** [comment]
I just found out: this is only a problem with custom difficulties, cause 7 works fine on the normal difficulties, and I think this is a problem with normal psych engine too so that needs to be fixed

**Comment by Lorekeeper49** [comment]
> if so, go to the json and turn it off

where even _is_ the json?

**Comment by snazzyostrich** [comment]
> > if so, go to the json and turn it off
> 
> where even _is_ the json?

wherever you saved it

**Comment by Lorekeeper49** [comment]
> > > if so, go to the json and turn it off
> > 
> > 
> > where even _is_ the json?
> 
> wherever you saved it

I mean by default

**Comment by Lorekeeper49** [comment]
okay, now it works
