### ISSUE TITLE
"perfect" asset missing in pixel stages

### ISSUE THREAD

**Issue by snazzyostrich** [weuz-github/FNF-OSEngine#16]
### Describe your bug here.

title says it all
i tried making one myself and naming the file "perfect-pixel" but nothing shows up
![image](https://user-images.githubusercontent.com/95659988/168496213-f1b1c5df-1da0-4338-964b-0764f6b94af2.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by weuz-github** [comment]
Yeah, i already know about it. Gonna fix it in new update

**Comment by weuz-github** [comment]
and did u put this assets to mods folder or assets folder?
if you put it into mods folder, try to put it to assets/shared/images/pixelUI (maybe it will work)

**Comment by snazzyostrich** [comment]
> and did u put this assets to mods folder or assets folder? if you put it into mods folder, try to put it to assets/shared/images/pixelUI (maybe it will work)

i did
