### ISSUE TITLE
week title being weird + afterimage broken

### ISSUE THREAD

**Issue by snazzyostrich** [weuz-github/FNF-OSEngine#17]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/95659988/168704745-81d44697-c24b-4fc1-aa4d-917e94a05d4e.png)
and after you change a character with character trails on, you get this
![image](https://user-images.githubusercontent.com/95659988/168704865-14ed1d6a-3c45-4fb5-ae73-1129b6d50941.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by weuz-github** [comment]
1.3.0 will fix it.

**Comment by snazzyostrich** [comment]
thx
