### ISSUE TITLE
how can I make shaders appear on a specific beat?

### ISSUE THREAD

**Issue by snazzyostrich** [weuz-github/FNF-OSEngine#18]
### Describe your problem here.

tried this, but they never show up
![image](https://user-images.githubusercontent.com/95659988/168705103-2e235583-e12c-4077-bec4-494dfff6da9d.png)
if you have an answer that would be greatly appreciated

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by itsDARK768** [comment]
You need to change onCreate to onBeatHit for beathit stuff, onCreate is usually used for things like makeLuaSprite.
