### ISSUE TITLE
stolen code without credit

### ISSUE THREAD

**Issue by nebulazorua** [weuz-github/FNF-OSEngine#20]
### What is your question?

if you're stealing code then add credit!!!!!

**Comment by weuz-github** [comment]
Well, what lines of code are stolen?

**Comment by weuz-github** [comment]
Well, what lines of code are stolen?

**Comment by weuz-github** [comment]
If you are about "addShaderToCamera" function, then its from old psych engine versions lol. I did not steal thia function from other engines lol

**Comment by weuz-github** [comment]
And yes, which credits should i add then?

**Comment by weuz-github** [comment]
closing because didn't get answer
